DependencyProject/Models/Account.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DependencyProject.Models
{
    public class Account
    {
        public int AccountId { get; set; }
        [Required]
        [Index(IsUnique = true)]
        [EmailAddress]
        [Display(Name = "Email")]
        [StringLength(500)]
        public string Email { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string  Password { get; set; }
        [Required]
        [StringLength(50, MinimumLength = 2)]
        public string FirstName { get; set; }
        [Required]
        [StringLength(50, MinimumLength = 2)]
        public string LastName { get; set; }
        public int AccountTypeId { get; set; }

    }
}

DependencyProject/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DependencyProject.Context;
using DependencyProject.Models;
using System.Security.Cryptography;
using System.Text;
using DependencyProject.Extensions;
using DependencyProject.Repositories;
using System.Web.Security;
using System.Net.Mail;
using DependencyProject.Enums;

namespace DependencyProject.Controllers
{
    public class AccountsController : Controller
    {
        //private AccountRepository _repository;

        //public AccountsController(AccountRepository repository)
        //{
        //    _repository = repository ?? new AccountRepository();
        //}
        ///// <summary>
        ///// GET: Accounts
        ///// </summary>
        ///// <returns>All accounts register in the system</returns>
        //[Authorize(Roles = "Admin,Manager")]
        //public ActionResult Index()
        //{
        //    return View(_repository.GetAll());
        //}

        //// 
        ///// <summary>
        ///// GET: Details of a selected account
        ///// </summary>
        ///// <param name="id"></param>
        ///// <returns>The account object</returns>
        //[Authorize(Roles = "Admin,Manager")]
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Account account = _repository.Get(id);
        //    if (account == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(account);
        //}

        ///// <summary>
        ///// GET: Create account form
        ///// </summary>
        ///// <returns>View</returns>
        //[Authorize(Roles = "Admin,Manager")]
        //public ActionResult Create()
        //{
        //    var accountTypeData = from AccountTypeEnum e in Enum.GetValues(typeof(AccountTypeEnum)) select new { ID = (int)e, Name = e.ToString() };
        //    ViewBag.AccountTypeId = new SelectList(accountTypeData, "ID", "Name");
        //    return View();
        //}

        ///// <summary>
        ///// POST: Accounts/Create
        ///// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        ///// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        ///// </summary>
        ///// <param name="account">Object account</param>
        ///// <returns>View with account object</returns>
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //[Authorize(Roles = "Admin,Manager")]
        //public ActionResult Create([Bind(Include = "AccountId,Email,Password,Name,AccountTypeId")] Account account)
        //{
        //    var accountTypeData = from AccountTypeEnum e in Enum.GetValues(typeof(AccountTypeEnum)) select new { ID = (int)e, Name = e.ToString() };
        //    ViewBag.AccountTypeId = new SelectList(accountTypeData, "ID", "Name", account.AccountTypeId);

        //    if (ModelState.IsValid)
        //    {
        //        List<Account> accounts = _repository.GetByEmail(account.Email);
        //        if (accounts.Count == 0) { 
        //            account.Password = Utils.Instance.Encript(account.Password);
        //            _repository.Add(account);
        //            _repository.SaveChanges();
        //            return RedirectToAction("Index");
        //        }
        //        else
        //        {
        //            ViewBag.Error = "This e-mail is already taken.";
        //        }
        //    }
        //    return View(account);
        //}

        ///// <summary>
        ///// GET: Edition of an existing account
        ///// </summary>
        ///// <param name="id">Account id</param>
        ///// <returns>View with account obkect</returns>
        //[Authorize(Roles = "Admin,Manager")]
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Account account = _repository.Get(id);
        //    if (account == null)
        //    {
        //        return HttpNotFound();
        //    }

        //    var accountTypeData = from AccountTypeEnum e in Enum.GetValues(typeof(AccountTypeEnum)) select new { ID = (int)e, Name = e.ToString() };
        //    ViewBag.AccountTypeId = new SelectList(accountTypeData, "ID", "Name", account.AccountTypeId);
        //    return View(account);
        //}

        ///// <summary>
        ///// POST: Accounts/Edit/5
        ///// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        ///// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        ///// </summary>
        ///// <param name="account">Account object</param>
        ///// <returns>Success:Index View, Fail:Error 500 View, Invalid Form: View Account object</returns>
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //[Authorize(Roles = "Admin,Manager")]
        //public ActionResult Edit([Bind(Include = "AccountId,Email,Password,Name,AccountTypeId")] Account account)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        List<Account> accounts = _repository.GetByEmail(account.Email);
        //        if (accounts.Count == 0 || account.AccountId == accounts[0].AccountId)
        //        {
        //            _repository = new AccountRepository();
        //            _repository.Edit(account);
        //            _repository.SaveChanges();
        //            return RedirectToAction("Index");
        //        }
        //        else
        //        {
        //            ViewBag.Error = "This e-mail is already taken.";
        //        }
        //    }
        //    var accountTypeData = from AccountTypeEnum e in Enum.GetValues(typeof(AccountTypeEnum)) select new { ID = (int)e, Name = e.ToString() };
        //    ViewBag.AccountTypeId = new SelectList(accountTypeData, "ID", "Name", account.AccountTypeId);
        //    return View(account);
        //}

        ///// <summary>
        ///// GET: Accounts/Delete/5
        ///// </summary>
        ///// <param name="id">Account id</param>
        ///// <returns>View account object</returns>
        //[Authorize(Roles = "Admin,Manager")]
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Account account = _repository.Get(id);
        //    if (account == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(account);
        //}

        ///// <summary>
        ///// POST: Accounts/Delete/5
        ///// </summary>
        ///// <param name="id">Account id</param>
        ///// <returns>Index view </returns>
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //[Authorize(Roles = "Admin,Manager")]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Account account = _repository.Get(id);
        //    _repository.Remove(account);
        //    _repository.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        ///// <summary>
        ///// GET: Login
        ///// </summary>
        ///// <returns>View</returns>
        //public ActionResult LogIn()
        //{
        //    return View();
        //}

        ///// <summary>
        ///// POST: Login
        ///// </summary>
        ///// <param name="account">Account object</param>
        ///// <returns>Success: Dashboard View, Error: View</returns>
        //[HttpPost]
        //public ActionResult LogIn([Bind(Include = "Email,Password")]Account account)
        //{
        //    Account objAccount = isValid(account.Email, account.Password);
        //    if (objAccount != null)
        //    {
        //        FormsAuthentication.SetAuthCookie(objAccount.Email, false);

        //        FormsAuthenticationTicket authTicket = new FormsAuthenticationTicket(
        //              1,
        //              objAccount.Email,  //user email
        //              DateTime.Now,
        //              DateTime.Now.AddDays(1),  // expiry
        //              false,  //do not remember
        //              Enum.GetName(typeof(AccountTypeEnum), objAccount.AccountTypeId),
        //              "/");
        //        HttpCookie cookie = new HttpCookie(FormsAuthentication.FormsCookieName,
        //                                           FormsAuthentication.Encrypt(authTicket));
        //        Response.Cookies.Add(cookie);
                
        //        return RedirectToAction("Index", "Home");
        //    }
        //    else
        //    {
        //        ViewBag.Error = "Email or Password are incorrect, please try again.";
        //        return View(account);
        //    }
        //}

        ///// <summary>
        ///// POST: Recover Password
        ///// </summary>
        ///// <param name="Email">E-mail address</param>
        ///// <returns>Send status:Fail, Success, Error</returns>
        //[HttpPost]
        //public ActionResult RecoverPassword(string Email)
        //{
        //    Random rnd = new Random();
        //    List<Account> accounts = _repository.GetByEmail(Email);
        //    string wasSend;

        //    if (accounts.Count > 0)
        //    {
        //        int intPass = rnd.Next(99999);
        //        try {
        //            accounts[0].Password = Utils.Instance.Encript(intPass.ToString());
        //            _repository.Edit(accounts[0]);
        //            _repository.SaveChanges();

DependencyProject/Views/Accounts/Create.cshtml
@model DependencyProject.Models.Account

@{
    ViewBag.Title = "Create";
}

<script>
    $(document).ready(function () {
        $('#rPassword').on('input', function (e) {
            validatePassword();
        });
        $('#Password').on('input', function (e) {
            validatePassword();
        });
    });

    function validatePassword() {
        if ($("#rPassword").val() != $("#Password").val()) {
            $("#PEMsg").show();
            $("#btnSubmit").prop('disabled', true);
            $("#PEMsg").text("The password is not the same.");
        } else {
            $("#PEMsg").hide();
            $("#btnSubmit").prop('disabled', false);
        }
    }

</script>
<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Account</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { id = "Password", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <lable class="control-label col-md-2" style="font-weight:bold">Repeat Password</lable>
            <div class="col-md-10">
                <input type="password" id="rPassword" name="rPassword" class="form-control">
                <label id="PEMsg" style="display:none"class="text-danger"></label>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AccountTypeId, "AccountTypeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AccountTypeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AccountTypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="btnSubmit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DependencyProject/Views/Accounts/Delete.cshtml
@model DependencyProject.Models.Account

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Account</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AccountTypes.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccountTypes.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DependencyProject/Views/Accounts/Details.cshtml
@model DependencyProject.Models.Account

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Account</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AccountTypes.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccountTypes.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.AccountId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DependencyProject/Views/Accounts/Edit.cshtml
@model DependencyProject.Models.Account

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Account</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.AccountId)

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="display:none;">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AccountTypeId, "AccountTypeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AccountTypeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AccountTypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DependencyProject/Views/Accounts/Index.cshtml
@model IEnumerable<DependencyProject.Models.Account>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.AccountTypeId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <td>
            @Html.DisplayNameFor(model => model.LastName)
        </td>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @(Enum.GetName(typeof(Web.UI.Enums.AccountTypeEnum), item.AccountTypeId))
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.AccountId }) |
            @Html.ActionLink("Details", "Details", new { id=item.AccountId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.AccountId })
        </td>
    </tr>
}

</table>

DependencyProject/Views/Accounts/LogIn.cshtml
@model DependencyProject.Models.Account

@{
    ViewBag.Title = "Log In";
}

<script>
    $(document).ready(function () {
        $('#recoverPasword').on('click', function () {
            var email = $('#emailInput').val();
            if (email != "") {
                $('#emailError').text("");
                recoverPassword(email);
            } else {
                $('#emailError').text("You must type your e-mail");
            }
        });
    });


    function recoverPassword(Email)
    {
        var EConditionOptions = {};
        EConditionOptions.url = "@Url.Action("RecoverPassword", "Accounts")";
        EConditionOptions.type = "POST";
        EConditionOptions.data = JSON.stringify({
            Email: Email
        });
        EConditionOptions.datatype = "json";
        EConditionOptions.contentType = "application/json";
        EConditionOptions.success = function (data) {
                switch(data){
                    case "True":
                        $('#Success').show();
                        $('#Success').text("Your e-mail has been send");
                        break;
                    case "False":
                        $('#Error').show();
                        $('#Error').text("Your e-mail could not be send, please try again");
                        break;
                    case "Error":
                        $('#Error').show();
                        $('#Error').text("There was an error, please try again");
                        break;
                }
        };
        $.ajax(EConditionOptions);
    }

</script>
<h2>Log In</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Account</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { id="emailInput",@class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { id="emailError",@class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Log In" class="btn btn-default" />
                <a id="recoverPasword" href="#">Recover Password</a>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>